channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - pyg
dependencies:
  - cudatoolkit-dev=11.7
  - python=3.10.*
  - cmake=3.14.0
  - pybind11
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch3d
  - torchvision
  - torchaudio
  - mkl=2024.0
  - pyg
  - pytorch-cluster
  - pytorch-scatter
  - exa # optional: nice ls
  - fzf # optional: fancy ctrl + R
  - pip
  - habitat-sim=0.3.3
  - pip:
    - gym>=0.22.0,<0.23.1
    - setuptools <70
    - yacs>=0.1.8
    - numpy-quaternion-2023.0.4
    - attrs>=19.1.0
    - numpy=1.23.5
    - scipy
    - sophuspy
    - pybullet
    - trimesh<4
    - pytest
    - scikit-image
    - scikit-fmm
    - scikit-learn
    - natsort
    - frozendict
    - opencv-python
    - pin>=2.6.17
    - openai-clip
    - timm
    - pandas>=2
    - mss
    - matplotlib>=3
    - click
    - pillow<10.0.0
    - atomicwrites
    - loguru
    - yacs
    - h5py>=3.9
    - imageio
    - pygifsicle
    - pynput
    - open3d>=0.17
